[package]
name = "rust-gql"
version = "0.1.0"
authors = ["rqrqrqrq <rqtdfh@gmail.com>"]

[dependencies]
dotenv="0.11"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
juniper = "0.9.0"
juniper_rocket = "0.1.2"
diesel = { version = "1.0", features = ["postgres"] }
